language: objective-c
osx_image: xcode8.3
xcode_workspace: FlyveMDMInventoryAgent.xcworkspace
xcode_scheme: FlyveMDMInventoryAgent
podfile: Podfile
before_install:
- chmod a+x scripts/add-key.sh
- chmod a+x scripts/run-build.sh
- chmod a+x scripts/remove-key.sh
- gem update --system
- gem install fastlane --no-rdoc --no-ri --no-document --quiet
install: true
before_script:
- "./scripts/add-key.sh"
- echo FASTLANE_PASSWORD=$FASTLANE_PASSWORD >> .env
- echo TELEGRAM_WEBHOOKS=$TELEGRAM_WEBHOOKS >> .env
- echo GIT_REPO=$TRAVIS_REPO_SLUG >> .env
- echo GIT_BRANCH=$TRAVIS_BRANCH >> .env
script:
- xcodebuild clean build -workspace FlyveMDMInventoryAgent.xcworkspace -scheme FlyveMDMInventoryAgent
- "./scripts/run-build.sh"
after_script:
- "./scripts/remove-key.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - APPNAME="FlyveMDMInventoryAgent"
  - PROFILE_UUID=XC_iOS_orgflyveinventoryagent
  - KEYCHAIN_NAME="ios-app.keychain"
  - SCRIPT_PATH=./scripts
  - CERTIFICATES_PATH=./scripts/cert
  - PROFILE_PATH=./scripts/profile
  - secure: Qd79zZzU7TgeODD2X1+MoDs32skMZjvJUCiS4wnxkEZ5EpYzojULIeZLGM9rtMYfQ/pv5Iz1vgaioH/pTQe0qDV3xDJCH5M7nRpGMt9WqgOFLwXpAiHUcm4es1v9j82ZuDw8NgxMxynSP8AjOa+TJl9hWTzxLR6vOkGwcXBKlounbG9teBZml2pVegVRguJ/7c55EQYjhUe7JjiqRoEzoUZEIHFyvHY8NTtbxjObpdGnN26J87PSJJST3Fw+R5WKRclatuTi0iH4XODi02aMPxbkzGj3wJwqY5GAqvtwpWfPx3nuEd1/zBiSwiDrbNHl6JpP4dktIpDq2w56FynyEeCiq2+njiJT+0Z8Z2K2jO5hr++JQnmufSsFbAYlZoO0DpcO1A2i3I2QvPYjJoXy1pxJytRj0RWN02ZTUFkaryRMB0WOYempcV/YF4FoGRiMRMwmBpAl3rqcRG7N3GtpkXU+GDa29/YXKCPW0T1Tcxr6XGcak5PpafziR/dkrq4TUoQZA4hcGZfUtriOdMOMBgEcXlVMY09iaqwele4CPEgp3RpuiMOK60C0UTuOzxEdS1eoxgTuvMhy7e58v80uUk/HhFTGgRL4m5tMvzUZiMkgKV0hjhSujyktP1MYtLHTgdJdWyopj2nr6PXGKLtAiU+U7bpSEkpSJbC8CDDV6ms=
  - secure: nWx9rVrIA/sgDylBfDINCwdsFDv/BnevS+S8yKgysuJ0d5zl418vo43KIKTyWNkZfksb0SLlTc1eDR47ChAKBYZlyQKDkDtduqY43kO+KsZ6KRazChBuQrz1+ckDnUuVd+eAL+yeUO1DxSGcJsVnhOPKp1UXdhGBrrnkTBgnHf3GTxD6XNaT6gFZO7+/BCodIVEVaqaE0p1Qn/S0a/AhNoOP49+q/JIFcdp35znvRiwM4dHWqAeGeIk7+grcq5Z1dNtktyOZdm8jdNzTaAIEM2K8jJviOA//hYNMcnd07CN0QD23nwcSmaO68RJBzpN/3/I0ymBdHXxRb4aLMoBmQUPOtksexxk7RND83mE23y/LNC3mNwYKY5ctaFtqI1Ad/tI+KV6nmGydqxhU35PuOJmUvVvawEx6lCAN5TnmAMc+SMQH07a8z6twgi/gH4KdTP53+0r08fVj/ueN0wevsbMcIW4zaucFrgKZssD7v2+lwie/yVIWyxtPVMiuyQplEpKZmaidBfVlJ/wyOEWiv7SdVgP6OXEcff2yjHVKZJciW4zH7xz4GU5C6OMqGTWB0RFPTKWzEQdwIBin+jpVje+XS/DlwAA0Pxuly/YfmB4RcmpNq4c+5p6M8Wzo5rR3dppywJZy49Jww4IFiVLEu/MmFnW7XFRWTdRVw0eqJRY=
  - secure: smaWIqUmtSeenDUlp1nBQC5oFrQqRAbxQGuAGmeDIOkvDLUsZ6Vy5wwDXgpiD6Etk05Ko57OllLd2ZXcwwQuj1A7k0mHfxMggZKxmfzGZJ9N4+GFuUWeB7ZKagR7CWB/sLO/4Y+tYD001SPKkjbA70ztNdV+G7xHtqKyzxUeVWfWDoPJqs6mObuNGn+xuObiZ/7MBc3Jz05kOQCo4nuD6lVQFDoVQybf32L9nkxJPOk8IhAvgaTMTuyI7sE9l9KDpFXmAd3+VNF6hBvue+l77R6LCfOnNgbikaaz4PHU4f4vMwaaPrcrGAG/07pR5xMtqjvhMh5HwgaVm8qtmRsKS3vYHRfo9eSlKM1VCzhUowXGGO44nnr57qId5Gq5s1ZhkbzIaD3NIAiOz8a3IkAvGhc3c+5rftoFn4YYorgOQ1mT8j3d5TzjkK6Q4hBaFLZfBNj3cn0zEHb35oQYOt0juy8v1WUTBrILm1o/ItPPOebLjIXPVuWeHYnnugfpczAbKtO9hNTRxYm7Gh8QiCC5hKVYu/hNmmao64DaCBLetqtbsvLvG0JcalgMoxoVe39obXll4ZA+w+QgU68SxCkO3r6/atlBOhkxF1gZcWSeG78YVeL7cNfjRRGrjHb1WDYqZJZxA1RX+XyYyOPczZMTqy9XPZq0vfgpUnQvfIc3gp0=
