# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8 Plus"
])

languages([
  "en-GB",
  "es-MX",
  "es-ES",
  "fr-FR",
  "ko",
  "pt-BR",
  "ru"
])

# The name of the scheme which contains the UI Tests
scheme ENV["XCODE_SCHEME_UI"]

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# clear all previously generated screenshots before creating new ones
clear_previous_screenshots true

# Don't open the HTML summary after running snapshot
skip_open_summary true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace ENV["XCODE_WORKSPACE"]

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
